### PR TITLE
Fixing the #4 issue.

### PR DESCRIPTION
**Pull request by francescomalatesta**
Here's my proposal, after many tests, of a fix for the #4 issue. Let me know what do you think!

### CODE REVIEW

**Comment by Swader** [comment]
@francescomalatesta have you tried it on Windows?

**Comment by Swader** [comment]
Actually, works on Windows but not on OS X. @francescomalatesta what platform did you test this on?

**Comment by Swader** [comment]
Actually, just re-tested and it seems to be fine

**Comment by francescomalatesta** [comment]
Sorry but Github seems to avoid notifications about that PR :( I'm happy it worked!

**Pull request merged**
